* arts-2-3-740
* CMakeLists.txt:

While OEM works fine with Clang now, Apple Clang is still not
cooperating -> disable OEM by default if Apple Clang is used.

Error: https://gist.github.com/olemke/a2d5b7621a425a245ee2180d52d6b7a7

git-svn-id: https://www.sat.ltu.se/svn/rt/arts/trunk@10548 aaf1aab0-4228-0410-ad68-8dceda47f409